{% set name = "hdwallets" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hukkin/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 59bda429e540845625e73ddbe598dfead640ade03db654b783d7f1d42058d015
  patches:
    - fix_mpz_utils.py.patch
    - fix_undefined_pubkey_bip32.py.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8
    - ecdsa

test:
  imports:
    - hdwallets
  source_files:
    - tests
  commands:
    - pip check
    - pytest -v tests/test_bip32.py
  requires:
    - pip
    - pytest
    - pytest-randomly
    - base58

about:
  home: https://github.com/hukkin/hdwallets
  summary: Python implementation of the BIP32 key derivation scheme
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MementoRC
